default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]  # make sure to include jupyter files
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli  # allows checking TOML files

ci:  # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: weekly
