name: 'Set versions'
description: 'Sets env variables with various software versions used in the workflows'

runs:
  using: 'composite'
  steps:
    - name: "set UV version"
      shell: bash
      run: echo "VERSION_UV=0.5.25" >> $GITHUB_ENV

    - name: "set Julia version"
      shell: bash
      run: echo "VERSION_JULIA=1.11.7" >> $GITHUB_ENV


